---
# General
- name: General - Stop playing sound effects
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.sound.uiaudio.enabled
    type: int
    value: 0
    state: present

- name: General - Disable Resume system-wide
  osx_defaults:
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    type: bool
    value: false
    state: present

- name: General - Disable automatic termination of inactive apps
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDisableAutomaticTermination
    type: bool
    value: true
    state: present

- name: Dark mode - Dark mode
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyle
    type: string
    value: Dark
    state: present

- name: iCloud - Save to disk (not icloud) by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    type: bool
    value: false
    state: present

- name: Show battery percentage
  osx_defaults:
    domain: com.apple.controlcenter.plist
    host: currentHost
    key: BatteryShowPercentage
    type: bool
    value: true
    state: present

# USB volumes
- name: USB volumes - Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    state: present

- name: USB volumes - Avoid creating .DS_Store files on USB volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true
    state: present

# screenshots
- name: Create screenshots directory
  file:
    path: '{{ ansible_env.HOME }}/Pictures/Screenshots'
    state: directory

- name: Screenshots - Save to screnshots directory
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    type: string
    value: '{{ ansible_env.HOME }}/Pictures/Screenshots'
    state: present

- name: Screenshots - Save to png
  osx_defaults:
    domain: com.apple.screencapture
    key: type
    type: string
    value: 'png'
    state: present
