# Trackpad
- name: Trackpad - Disable natural scrolling
  osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    type: bool
    value: false
    state: present

- name: Bluetooth - Increase sound quality
  osx_defaults:
    domain: com.apple.BluetoothAudioAgent
    key: "Apple Bitpool Min (editable)"
    type: int
    value: 40
    state: present

# Keyboard
- name: General - Disable automatic capitalization
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false
    state: present

- name: General - Disable smart dashes
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: General - Disable automatic period substitution
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: General - Disable smart quotes
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: false
    state: present

- name: General - Disable auto-correct
  osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false
    state: present

- name: General - Enable Tab in modal dialogs
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    type: int
    value: 3
    state: present

- name: Keyboard - Disable press-and-hold for keys
  osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
    state: present

- name: Keyboard - set key repeat to fast
  osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
    state: present

- name: Keyboard - set initial key repeat to fast
  osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15
    state: present
