- name: Install homebrew cask cloud packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - google-cloud-sdk

- name: Install homebrew cloud packages
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli
    - azure-cli
    - teleport
    - tfenv
