---
- name: "Configuring MacOS on M1 macbook pro"
  hosts: localhost
  connection: local
  roles:
    - { role: homebrew, tags: [brew] }
    - { role: osx-defaults, tags: [osx] }
    - { role: user, tags: [user] }
    - { role: yubikey, tags: [never, gpg] }
