---
- name: Download google-cloud apt gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/google-cloud-achive-keyring.gpg

- name: Add google-cloud-sdk apt-repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-cloud-achive-keyring.gpg] http://packages.cloud.google.com/apt cloud-sdk main"
    filename: google-cloud-sdk

- name: Add kubernetes apt-repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-cloud-achive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    filename: kubernetes

# impish has no repo yet
- name: Add azure-cli apt-repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-achive-keyring.gpg] https://packages.microsoft.com/repos/azure-cli/ focal main"
    filename: azure-cli

- name: Download hashicorp apt gpg key
  apt_key:
    url: "https://apt.releases.hashicorp.com/gpg"
    keyring: /usr/share/keyrings/hashicorp-achive-keyring.gpg

- name: Add hashicorp apt-repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-achive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    filename: hashicorp

- name: Download github apt gpg key
  apt_key:
    url: "https://cli.github.com/packages/githubcli-archive-keyring.gpg"
    keyring: /usr/share/keyrings/github-achive-keyring.gpg

- name: Add github apt-repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/github-achive-keyring.gpg] https://cli.github.com/packages stable main"
    filename: github

- name: Download teleport apt gpg key
  apt_key:
    url: "https://deb.releases.teleport.dev/teleport-pubkey.asc"
    keyring: /usr/share/keyrings/teleport-achive-keyring.gpg

- name: Add teleport apt-repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/teleport-achive-keyring.gpg] https://deb.releases.teleport.dev/ stable main"
    filename: teleport
