- name: Parse Gnome Shell version
  shell: gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: parse_gnome_shell_version
  changed_when: no

- set_fact:
    gnome_shell_version: "{{ parse_gnome_shell_version.stdout }}"

- name: Install gnome extensions
  include_tasks: gnome_extensions.yml
  with_items:
    - "19"
    - "906"

- name: Configure keyboard caps to esc
  dconf:
    key: "/org/gnome/desktop/input-sources/xkb-options"
    value: "['caps:escape']"

- name: Configure system76 hidpi
  dconf:
    key: "/com/system76/hidpi/enable"
    value: "false"

- name: Configure clock format
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"

- name: Show week day
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "true"

- name: Enable hot corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "true"

- name: Show battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "true"

- name: Set nordic theme
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Nordic-darker-standard-buttons-v40'"

- name: Set nordic icon theme
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'Nordic-Darker'"

- name: Set default icon pack
  lineinfile:
    path: '{{ ansible_env.HOME }}/.local/share/icons/Nordic-Darker/index.theme'
    regexp: '^Inherits=.*$'
    line: 'Inherits=Pop,Papirus-Dark,ubuntu-mono-dark,elementary,gnome,hicolor'
    backrefs: yes

- name: Change power button action
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/power-button-action"
    value: "'suspend'"

- name: Hide dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "false"

- name: Configure dock on all monitors
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor"
    value: "true"

- name: Apply theme to dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme"
    value: "true"

- name: Apply theme to dock
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink"
    value: "true"

- name: Set dock's size
  dconf:
    key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: "44"

- name: Disable recent files
  dconf:
    key: "/org/gnome/desktop/privacy/remember-recent-files"
    value: "false"

- name: Allow loud volume
  dconf:
    key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "true"

- name: Add dcci brightness down shortcut binding
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding"
    value: "'<Primary>MonBrightnessDown'"

- name: Add dcci brightness down shortcut command
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command"
    value: "'light -s sysfs/backlight/ddcci9 -U 5'"

- name: Add dcci brightness down shortcut name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name"
    value: "'ddcci backlight down'"

- name: Add dcci brightness up shortcut binding
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding"
    value: "'<Primary>MonBrightnessUp'"

- name: Add dcci brightness up shortcut command
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command"
    value: "'light -s sysfs/backlight/ddcci9 -A 5'"

- name: Add dcci brightness up shortcut name
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name"
    value: "'ddcci backlight up'"

- name: Add shortcut bindings
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    value: ['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']

- name: Add screenshot shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/screenshot"
    value: ['Print', '<Shift><Super>numbersign']

- name: Add area screenshot shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/area-screenshot"
    value: ['<Shift>Print', '<Shift><Super>dollar']

- name: Add mute shortcut
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/mic-mute"
    value: ['<Shift><Super>a']

- name: Set workspaces on primary display only
  dconf:
    key: "/org/gnome/mutter/workspaces-only-on-primary"
    value: "true"

- name: Set workspaces on right side
  dconf:
    key: "/org/gnome/shell/extensions/pop-cosmic/workspace-picker-left"
    value: "false"

- name: Disable workspaces bar bug
  dconf:
    key: "/org/gnome/shell/extensions/cosmic-workspaces/panel-in-overview"
    value: "false"

- name: Configure pop-shell tilling
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/tile-by-default"
    value: "true"

- name: Disable pop-shell active-hint
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/active-hint"
    value: "false"

- name: Set pop-shell active-hint color
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/hint-color-rgba"
    value: "'rgb(129,161,193)'"

- name: Configure pop-shell inner gap
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/gap-inner"
    value: "uint32 1"

- name: Configure pop-shell outer gap
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/gap-outer"
    value: "uint32 1"

- name: Hide pop-shell window titles
  dconf:
    key: "/org/gnome/shell/extensions/pop-shell/show-title"
    value: "false"

- name: Set gnome-shell theme
  dconf:
    key: "/org/gnome/shell/extensions/user-theme/name"
    value: "'Nordic-darker-standard-buttons-v40'"

- name: Focus follow the mouse
  dconf:
    key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "'sloppy'"
